stats-server:
  name: ewm-service
  url: http://stat-service-container:9090
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-db
    username: sa
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: "true"
    show-sql: "true"
  sql:
    init:
      mode: always