server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewm-db
    username: sa
    password: 12345

  jpa:
    properties:
      hibernate:
        format_sql: "true"
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

client:
  url: http://stats-server:9090