services:
  stats-service:
    build: stats-service/stat-server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345