services:
  stats-server:
    build: stats-service/stat-server
    image: postImage
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
        - SPRING_DATASOURCE_USERNAME=ewm
        - SPRING_DATASOURCE_PASSWORD=ewm

  wm-db:
    image: postgres:16.1
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
      POSTGRES_DB: ewm-db