services:
  stats-server:
    build: stats-service/stat-server
    image: post_image
    container_name: stats_container
    ports:
      - "9090:8080"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
        - SPRING_DATASOURCE_USERNAME=sa
        - SPRING_DATASOURCE_PASSWORD=12345
        - STATS_SERVICE_URL=http://stat-service-container:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-container
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ewm-db