server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://stats-db:5433/explore_with_me
    username: sa
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: "true"